package aether.lexer;

public enum TokenType {
    // Delimiters
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA, SEMICOLON,

    // Operators
    ASSIGN, EQUAL_EQUAL, BANG_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    MINUS, PLUS, SLASH, STAR, BANG,

    // Literals & Identifiers
    IDENTIFIER, STRING, NUMBER,

    // Keywords
    MANIFEST, FLUX, ELSE, CYCLE, REVEAL, TRUE, FALSE, NIL, EOF
}
